language: php

php:
    - 5.3

env:
    - DB=mysql

before_script:
    - mysql -e 'create database qcubed;'
    - mysql -u root qcubed < assets/_core/php/examples/mysql_innodb.sql

script: travis/test.php